#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --architectures amd64 \
    --linux-packages "linux-image linux-headers" \
    --linux-flavours "6.19.0-g3c13c881adf4" \
    --binary-images iso-hybrid \
    --bootloader syslinux \
    --memtest none \
    --initramfs live-boot \
    --iso-application "NetLinux Desktop" \
    --iso-publisher "NetLinux https://netlinux.co.uk" \
    --iso-volume "NetLinux Desktop" \
    --apt-indices false \
    --security false \
    --firmware-chroot true \
    --mirror-bootstrap http://deb.debian.org/debian \
    --mirror-chroot http://deb.debian.org/debian \
    --mirror-binary http://deb.debian.org/debian \
    --initsystem systemd \
    "${@}"
